[package]
name = "uniffi_bindings_tests"
version = "0.29.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
thiserror = "1"
uniffi = { workspace = true, features = ["ffi-trace"] }

[features]
default = ["simple_fns", "primitive_types", "complex_fns", "compound_types", "records", "enums",
    "interfaces", "custom_types", "errors", "callback_interfaces", "futures"]
simple_fns = []
primitive_types = []
complex_fns = []
compound_types = []
records = []
enums = []
interfaces = []
custom_types = []
errors = []
callback_interfaces = []
futures = []
