[DEFAULT]
subsuite = "webgpu"
run-if = ["!release_or_beta"]
skip-if = ["verify"] # `test-verify` jobs don't guarantee a GPU, so skip them.
prefs = [
  "dom.webgpu.enabled=true",
  "dom.webgpu.workers.enabled=true",
  "privacy.fingerprintingProtection=true",
  "privacy.fingerprintingProtection.overrides='-AllTargets,+WebGPULimits'",
]

# WebGPU is only available in secure contexts.
#
# See spec WebIDL, like this: https://www.w3.org/TR/webgpu/#navigatorgpu
scheme = "https"

["test_rfp_clamp_limits_on.html"]
