[package]
name = "uniffi-bindgen-gecko-js-test-fixtures"
version = "0.29.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
uniffi_bindings_tests = { path = "../uniffi_bindings_tests" }
uniffi_bindings_tests_external_types = { path = "../uniffi_bindings_tests_external_types" }
uniffi_bindings_tests_collision = { path = "../uniffi_bindings_tests_collision" }
