# Configure UniFFI sources
#
# Each key is the UDL namespace of the component.
#
#
# IMPORTANT: Please Request review from a DOM peer before
# committing to using UniFFI. There are other ways to consume Rust from
# JavaScript that might fit your use case better.

# TODO: Upgrade the TOML crate and switch to array of tables syntax.


[suggest.receiver_thread]
default = "worker"
main = [
  "raw_suggestion_url_matches",
  "SuggestStore",
  "SuggestStore.interrupt",
  "SuggestStoreBuilder",
  "SuggestStoreBuilder.data_path",
  "SuggestStoreBuilder.load_extension",
  "SuggestStoreBuilder.remote_settings_bucket_name",
  "SuggestStoreBuilder.remote_settings_server",
  "SuggestStoreBuilder.build",
]

[relevancy.receiver_thread]
default = "worker"
main = [
  "RelevancyStore",
  "RelevancyStore.close",
  "RelevancyStore.interrupt",
  "score",
]

[remote_settings.receiver_thread]
default = "worker"
main = [
  "RemoteSettings",
]

[uniffi_fixture_refcounts.receiver_thread]
default = "main"

[uniffi_trait_interfaces.receiver_thread]
default = "main"

[uniffi_fixture_callbacks.receiver_thread]
default = "worker"
main = [
  "log_even_numbers_main_thread",
]
