# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
name: mozperftest
manifest: None
static-only: False
suites:
    netwerk/test/perf:
        description: "Performance tests from the 'network/test/perf' folder."
        tests:
            youtube-scroll: ""
            facebook-scroll: ""
            cloudflare: ""
            controlled: ""
            g-search: ""
            g-image: ""
            lq-fetch: ""
            youtube-noscroll: ""
    netwerk/test/unit:
        description: "Performance tests from the 'netwerk/test/unit' folder."
        tests:
            http3 raw: ""
    testing/performance:
        description: "Performance tests from the 'testing/performance' folder."
        tests:
            Politico Link: ""
            BBC Link: ""
            JSConf (cold): ""
            Facebook: ""
            YouTube Link: ""
            pageload: ""
            JSConf (warm): ""
            perfstats: ""
            webpagetest-firefox: ""
            webpagetest-chrome: ""

    browser/base/content/test:
        description: "Performance tests from the 'browser/base/content/test' folder."
        tests:
            Dom-size: ""

    browser/components/translations/tests/browser:
        description: "Performance tests for Translations models on Firefox Desktop"
        tests:
            "Full-Page Translation (Spanish to English)": ""

    dom/serviceworkers/test/performance:
        description: "Performance tests running through Mochitest for Service Workers"
        tests:
            "Service Worker Caching": ""
            "Service Worker Fetch": ""
            "Service Worker Registration": ""
            "Service Worker Update": ""

    toolkit/components/ml/tests/browser:
        description: "Performance tests running through Mochitest for ML Models"
        tests:
            "browser_ml_engine_perf.js": ""
            "browser_ml_engine_multi_perf.js": ""
            "ML Semantic History Search": ""
            "browser_ml_suggest_feature_perf.js": ""
            "browser_ml_suggest_inference.js": ""
            "browser_ml_autofill_perf.js": ""
            "browser_ml_summarizer_perf.js": ""
            "ML Smart Tab Clustering": ""
            "browser_ml_smart_tab_perf.js": ""
            "browser_ml_llama_summarizer_perf.js": ""

    intl/benchmarks/test/xpcshell:
        description: "Performance tests running through XPCShell for Intl code"
        tests:
            "IntlDateTimeFormat": ""
            "IntlLocale": ""
            "IntlNumberFormat": ""
            "IntlPluralRules": ""

    dom/webgpu/tests/mochitest:
        description: "Performance tests from the 'dom/webgpu/tests/mochitest' folder."
        tests:
            "Queue Write": ""
