[DEFAULT]
tags = "devtools"
head = "xpcshell-head.js"
firefox-appdir = "browser"
support-files = ["adb.py"]
run-if = ["os != 'android'"]

["test_adb.js"]
run-sequentially = "An extension having the same id is installed/uninstalled in different tests"

["test_prepare-tcp-connection.js"]
